### ISSUE TITLE
Milestone 2 doesn't run because "graphics not open"

### ISSUE THREAD

**Issue by marksherman** [oplS16projects/Chess-Mates-Josh-and-Connor-#2]
Not sure what the pathology is. Require further instruction or fix. 

<img width="498" alt="screen shot 2016-04-24 at 1 40 11 pm" src="https://cloud.githubusercontent.com/assets/2035149/14769219/2bf2e344-0a22-11e6-8fc2-5e6f3510fa94.png">

**Comment by cfinegan** [comment]
Hi Mark,

Sorry for the confusion, we had some trouble getting the GUI portion of the project to work. We got it fixed yesterday though, so I made a new release (v0.3) that should have all of our original goals for Milestone 2. Please let me know if you have any issues getting v0.3 to run.
