### ISSUE TITLE
website is missing connor's favorite expression

### ISSUE THREAD

**Issue by marksherman** [oplS16projects/Chess-Mates-Josh-and-Connor-#3]
Something has clearly gone wrong. Please fix and notify when ready.

@cfinegan

**Comment by cfinegan** [comment]
I've added my favorite expression to the gh-pages for the project. I've also attached a screenshot of my description, in case git-hub decides to delete my contribution again.

![procedure-desc](https://cloud.githubusercontent.com/assets/17788975/14903771/7ed9cc56-0d71-11e6-9438-6af69de1ee60.png)

**Comment by marksherman** [comment]
👍
